export enum ERoutes {
  dashboard = 'dashboard',
  profile = 'profile',
  users = 'users',
  employees = 'employees',
  opportunities = 'opportunities',
  auth = 'auth',
  login = 'login',
  verification = 'verification',
  signup = 'signup',
  register = 'register',
  verifyEmail = 'verify-email',
  forgotPassword = 'forgot-password',
  resetPassword = 'reset-password',
  unauthorizedInternalUser = 'unauthorized-internal-user',
  anonymous = 'public',
  admin = 'admin',
  investors = 'vendors',
  dvManager = 'dv-manager',
  settings = 'settings',
  holidaysManagement = 'holidays-management',
  plans = 'plans',
  myProfile = 'my-profile'
}
