import { ICountry } from './phone-input.interface';

// Helper function to get flag URL from country code
const getFlagUrl = (code: string): string => {
	// Convert country code to lowercase for flagcdn.com
	const lowerCode = code.toLowerCase();
	return `https://flagcdn.com/w20/${lowerCode}.png`;
};

export const COUNTRIES: ICountry[] = [
	{ code: 'US', name: 'United States', dialCode: '+1', flagUrl: getFlagUrl('US') },
	{ code: 'GB', name: 'United Kingdom', dialCode: '+44', flagUrl: getFlagUrl('GB') },
	{ code: 'CA', name: 'Canada', dialCode: '+1', flagUrl: getFlagUrl('CA') },
	{ code: 'AU', name: 'Australia', dialCode: '+61', flagUrl: getFlagUrl('AU') },
	{ code: 'DE', name: 'Germany', dialCode: '+49', flagUrl: getFlagUrl('DE') },
	{ code: 'FR', name: 'France', dialCode: '+33', flagUrl: getFlagUrl('FR') },
	{ code: 'IT', name: 'Italy', dialCode: '+39', flagUrl: getFlagUrl('IT') },
	{ code: 'ES', name: 'Spain', dialCode: '+34', flagUrl: getFlagUrl('ES') },
	{ code: 'NL', name: 'Netherlands', dialCode: '+31', flagUrl: getFlagUrl('NL') },
	{ code: 'BE', name: 'Belgium', dialCode: '+32', flagUrl: getFlagUrl('BE') },
	{ code: 'CH', name: 'Switzerland', dialCode: '+41', flagUrl: getFlagUrl('CH') },
	{ code: 'AT', name: 'Austria', dialCode: '+43', flagUrl: getFlagUrl('AT') },
	{ code: 'SE', name: 'Sweden', dialCode: '+46', flagUrl: getFlagUrl('SE') },
	{ code: 'NO', name: 'Norway', dialCode: '+47', flagUrl: getFlagUrl('NO') },
	{ code: 'DK', name: 'Denmark', dialCode: '+45', flagUrl: getFlagUrl('DK') },
	{ code: 'FI', name: 'Finland', dialCode: '+358', flagUrl: getFlagUrl('FI') },
	{ code: 'PL', name: 'Poland', dialCode: '+48', flagUrl: getFlagUrl('PL') },
	{ code: 'CZ', name: 'Czech Republic', dialCode: '+420', flagUrl: getFlagUrl('CZ') },
	{ code: 'GR', name: 'Greece', dialCode: '+30', flagUrl: getFlagUrl('GR') },
	{ code: 'PT', name: 'Portugal', dialCode: '+351', flagUrl: getFlagUrl('PT') },
	{ code: 'IE', name: 'Ireland', dialCode: '+353', flagUrl: getFlagUrl('IE') },
	{ code: 'NZ', name: 'New Zealand', dialCode: '+64', flagUrl: getFlagUrl('NZ') },
	{ code: 'JP', name: 'Japan', dialCode: '+81', flagUrl: getFlagUrl('JP') },
	{ code: 'KR', name: 'South Korea', dialCode: '+82', flagUrl: getFlagUrl('KR') },
	{ code: 'CN', name: 'China', dialCode: '+86', flagUrl: getFlagUrl('CN') },
	{ code: 'IN', name: 'India', dialCode: '+91', flagUrl: getFlagUrl('IN') },
	{ code: 'SG', name: 'Singapore', dialCode: '+65', flagUrl: getFlagUrl('SG') },
	{ code: 'MY', name: 'Malaysia', dialCode: '+60', flagUrl: getFlagUrl('MY') },
	{ code: 'TH', name: 'Thailand', dialCode: '+66', flagUrl: getFlagUrl('TH') },
	{ code: 'ID', name: 'Indonesia', dialCode: '+62', flagUrl: getFlagUrl('ID') },
	{ code: 'PH', name: 'Philippines', dialCode: '+63', flagUrl: getFlagUrl('PH') },
	{ code: 'VN', name: 'Vietnam', dialCode: '+84', flagUrl: getFlagUrl('VN') },
	{ code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flagUrl: getFlagUrl('SA') },
	{ code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flagUrl: getFlagUrl('AE') },
	{ code: 'KW', name: 'Kuwait', dialCode: '+965', flagUrl: getFlagUrl('KW') },
	{ code: 'QA', name: 'Qatar', dialCode: '+974', flagUrl: getFlagUrl('QA') },
	{ code: 'BH', name: 'Bahrain', dialCode: '+973', flagUrl: getFlagUrl('BH') },
	{ code: 'OM', name: 'Oman', dialCode: '+968', flagUrl: getFlagUrl('OM') },
	{ code: 'JO', name: 'Jordan', dialCode: '+962', flagUrl: getFlagUrl('JO') },
	{ code: 'LB', name: 'Lebanon', dialCode: '+961', flagUrl: getFlagUrl('LB') },
	{ code: 'EG', name: 'Egypt', dialCode: '+20', flagUrl: getFlagUrl('EG') },
	{ code: 'ZA', name: 'South Africa', dialCode: '+27', flagUrl: getFlagUrl('ZA') },
	{ code: 'NG', name: 'Nigeria', dialCode: '+234', flagUrl: getFlagUrl('NG') },
	{ code: 'KE', name: 'Kenya', dialCode: '+254', flagUrl: getFlagUrl('KE') },
	{ code: 'GH', name: 'Ghana', dialCode: '+233', flagUrl: getFlagUrl('GH') },
	{ code: 'BR', name: 'Brazil', dialCode: '+55', flagUrl: getFlagUrl('BR') },
	{ code: 'MX', name: 'Mexico', dialCode: '+52', flagUrl: getFlagUrl('MX') },
	{ code: 'AR', name: 'Argentina', dialCode: '+54', flagUrl: getFlagUrl('AR') },
	{ code: 'CL', name: 'Chile', dialCode: '+56', flagUrl: getFlagUrl('CL') },
	{ code: 'CO', name: 'Colombia', dialCode: '+57', flagUrl: getFlagUrl('CO') },
	{ code: 'PE', name: 'Peru', dialCode: '+51', flagUrl: getFlagUrl('PE') },
	{ code: 'VE', name: 'Venezuela', dialCode: '+58', flagUrl: getFlagUrl('VE') },
	{ code: 'RU', name: 'Russia', dialCode: '+7', flagUrl: getFlagUrl('RU') },
	{ code: 'TR', name: 'Turkey', dialCode: '+90', flagUrl: getFlagUrl('TR') },
	{ code: 'IL', name: 'Israel', dialCode: '+972', flagUrl: getFlagUrl('IL') },
	{ code: 'PK', name: 'Pakistan', dialCode: '+92', flagUrl: getFlagUrl('PK') },
	{ code: 'BD', name: 'Bangladesh', dialCode: '+880', flagUrl: getFlagUrl('BD') },
	{ code: 'LK', name: 'Sri Lanka', dialCode: '+94', flagUrl: getFlagUrl('LK') },
	{ code: 'MM', name: 'Myanmar', dialCode: '+95', flagUrl: getFlagUrl('MM') },
	{ code: 'KH', name: 'Cambodia', dialCode: '+855', flagUrl: getFlagUrl('KH') },
	{ code: 'LA', name: 'Laos', dialCode: '+856', flagUrl: getFlagUrl('LA') },
	{ code: 'BN', name: 'Brunei', dialCode: '+673', flagUrl: getFlagUrl('BN') },
	{ code: 'TW', name: 'Taiwan', dialCode: '+886', flagUrl: getFlagUrl('TW') },
	{ code: 'HK', name: 'Hong Kong', dialCode: '+852', flagUrl: getFlagUrl('HK') },
	{ code: 'MO', name: 'Macau', dialCode: '+853', flagUrl: getFlagUrl('MO') },
	{ code: 'MN', name: 'Mongolia', dialCode: '+976', flagUrl: getFlagUrl('MN') },
	{ code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flagUrl: getFlagUrl('KZ') },
	{ code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flagUrl: getFlagUrl('UZ') },
	{ code: 'AF', name: 'Afghanistan', dialCode: '+93', flagUrl: getFlagUrl('AF') },
	{ code: 'IR', name: 'Iran', dialCode: '+98', flagUrl: getFlagUrl('IR') },
	{ code: 'IQ', name: 'Iraq', dialCode: '+964', flagUrl: getFlagUrl('IQ') },
	{ code: 'SY', name: 'Syria', dialCode: '+963', flagUrl: getFlagUrl('SY') },
	{ code: 'YE', name: 'Yemen', dialCode: '+967', flagUrl: getFlagUrl('YE') },
	{ code: 'PS', name: 'Palestine', dialCode: '+970', flagUrl: getFlagUrl('PS') },
	{ code: 'MA', name: 'Morocco', dialCode: '+212', flagUrl: getFlagUrl('MA') },
	{ code: 'DZ', name: 'Algeria', dialCode: '+213', flagUrl: getFlagUrl('DZ') },
	{ code: 'TN', name: 'Tunisia', dialCode: '+216', flagUrl: getFlagUrl('TN') },
	{ code: 'LY', name: 'Libya', dialCode: '+218', flagUrl: getFlagUrl('LY') },
	{ code: 'SD', name: 'Sudan', dialCode: '+249', flagUrl: getFlagUrl('SD') },
	{ code: 'ET', name: 'Ethiopia', dialCode: '+251', flagUrl: getFlagUrl('ET') },
	{ code: 'TZ', name: 'Tanzania', dialCode: '+255', flagUrl: getFlagUrl('TZ') },
	{ code: 'UG', name: 'Uganda', dialCode: '+256', flagUrl: getFlagUrl('UG') },
	{ code: 'RW', name: 'Rwanda', dialCode: '+250', flagUrl: getFlagUrl('RW') },
	{ code: 'ZM', name: 'Zambia', dialCode: '+260', flagUrl: getFlagUrl('ZM') },
	{ code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flagUrl: getFlagUrl('ZW') },
	{ code: 'BW', name: 'Botswana', dialCode: '+267', flagUrl: getFlagUrl('BW') },
	{ code: 'NA', name: 'Namibia', dialCode: '+264', flagUrl: getFlagUrl('NA') },
	{ code: 'MZ', name: 'Mozambique', dialCode: '+258', flagUrl: getFlagUrl('MZ') },
	{ code: 'AO', name: 'Angola', dialCode: '+244', flagUrl: getFlagUrl('AO') },
	{ code: 'SN', name: 'Senegal', dialCode: '+221', flagUrl: getFlagUrl('SN') },
	{ code: 'CI', name: 'Ivory Coast', dialCode: '+225', flagUrl: getFlagUrl('CI') },
	{ code: 'CM', name: 'Cameroon', dialCode: '+237', flagUrl: getFlagUrl('CM') },
	{ code: 'CD', name: 'DR Congo', dialCode: '+243', flagUrl: getFlagUrl('CD') },
	{ code: 'CG', name: 'Congo', dialCode: '+242', flagUrl: getFlagUrl('CG') },
	{ code: 'GA', name: 'Gabon', dialCode: '+241', flagUrl: getFlagUrl('GA') },
	{ code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flagUrl: getFlagUrl('GQ') },
	{ code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', flagUrl: getFlagUrl('ST') },
	{ code: 'CV', name: 'Cape Verde', dialCode: '+238', flagUrl: getFlagUrl('CV') },
	{ code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flagUrl: getFlagUrl('GW') },
	{ code: 'GN', name: 'Guinea', dialCode: '+224', flagUrl: getFlagUrl('GN') },
	{ code: 'SL', name: 'Sierra Leone', dialCode: '+232', flagUrl: getFlagUrl('SL') },
	{ code: 'LR', name: 'Liberia', dialCode: '+231', flagUrl: getFlagUrl('LR') },
	{ code: 'TG', name: 'Togo', dialCode: '+228', flagUrl: getFlagUrl('TG') },
	{ code: 'BJ', name: 'Benin', dialCode: '+229', flagUrl: getFlagUrl('BJ') },
	{ code: 'NE', name: 'Niger', dialCode: '+227', flagUrl: getFlagUrl('NE') },
	{ code: 'BF', name: 'Burkina Faso', dialCode: '+226', flagUrl: getFlagUrl('BF') },
	{ code: 'ML', name: 'Mali', dialCode: '+223', flagUrl: getFlagUrl('ML') },
	{ code: 'MR', name: 'Mauritania', dialCode: '+222', flagUrl: getFlagUrl('MR') },
	{ code: 'TD', name: 'Chad', dialCode: '+235', flagUrl: getFlagUrl('TD') },
	{ code: 'CF', name: 'Central African Republic', dialCode: '+236', flagUrl: getFlagUrl('CF') },
	{ code: 'SS', name: 'South Sudan', dialCode: '+211', flagUrl: getFlagUrl('SS') },
	{ code: 'ER', name: 'Eritrea', dialCode: '+291', flagUrl: getFlagUrl('ER') },
	{ code: 'DJ', name: 'Djibouti', dialCode: '+253', flagUrl: getFlagUrl('DJ') },
	{ code: 'SO', name: 'Somalia', dialCode: '+252', flagUrl: getFlagUrl('SO') },
	{ code: 'KM', name: 'Comoros', dialCode: '+269', flagUrl: getFlagUrl('KM') },
	{ code: 'MU', name: 'Mauritius', dialCode: '+230', flagUrl: getFlagUrl('MU') },
	{ code: 'SC', name: 'Seychelles', dialCode: '+248', flagUrl: getFlagUrl('SC') },
	{ code: 'MG', name: 'Madagascar', dialCode: '+261', flagUrl: getFlagUrl('MG') },
	{ code: 'MV', name: 'Maldives', dialCode: '+960', flagUrl: getFlagUrl('MV') },
	{ code: 'NP', name: 'Nepal', dialCode: '+977', flagUrl: getFlagUrl('NP') },
	{ code: 'BT', name: 'Bhutan', dialCode: '+975', flagUrl: getFlagUrl('BT') },
	{ code: 'IS', name: 'Iceland', dialCode: '+354', flagUrl: getFlagUrl('IS') },
	{ code: 'LU', name: 'Luxembourg', dialCode: '+352', flagUrl: getFlagUrl('LU') },
	{ code: 'MT', name: 'Malta', dialCode: '+356', flagUrl: getFlagUrl('MT') },
	{ code: 'CY', name: 'Cyprus', dialCode: '+357', flagUrl: getFlagUrl('CY') },
	{ code: 'AL', name: 'Albania', dialCode: '+355', flagUrl: getFlagUrl('AL') },
	{ code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flagUrl: getFlagUrl('BA') },
	{ code: 'HR', name: 'Croatia', dialCode: '+385', flagUrl: getFlagUrl('HR') },
	{ code: 'RS', name: 'Serbia', dialCode: '+381', flagUrl: getFlagUrl('RS') },
	{ code: 'ME', name: 'Montenegro', dialCode: '+382', flagUrl: getFlagUrl('ME') },
	{ code: 'MK', name: 'North Macedonia', dialCode: '+389', flagUrl: getFlagUrl('MK') },
	{ code: 'SI', name: 'Slovenia', dialCode: '+386', flagUrl: getFlagUrl('SI') },
	{ code: 'SK', name: 'Slovakia', dialCode: '+421', flagUrl: getFlagUrl('SK') },
	{ code: 'HU', name: 'Hungary', dialCode: '+36', flagUrl: getFlagUrl('HU') },
	{ code: 'RO', name: 'Romania', dialCode: '+40', flagUrl: getFlagUrl('RO') },
	{ code: 'BG', name: 'Bulgaria', dialCode: '+359', flagUrl: getFlagUrl('BG') },
	{ code: 'EE', name: 'Estonia', dialCode: '+372', flagUrl: getFlagUrl('EE') },
	{ code: 'LV', name: 'Latvia', dialCode: '+371', flagUrl: getFlagUrl('LV') },
	{ code: 'LT', name: 'Lithuania', dialCode: '+370', flagUrl: getFlagUrl('LT') },
	{ code: 'BY', name: 'Belarus', dialCode: '+375', flagUrl: getFlagUrl('BY') },
	{ code: 'UA', name: 'Ukraine', dialCode: '+380', flagUrl: getFlagUrl('UA') },
	{ code: 'MD', name: 'Moldova', dialCode: '+373', flagUrl: getFlagUrl('MD') },
	{ code: 'GE', name: 'Georgia', dialCode: '+995', flagUrl: getFlagUrl('GE') },
	{ code: 'AM', name: 'Armenia', dialCode: '+374', flagUrl: getFlagUrl('AM') },
	{ code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flagUrl: getFlagUrl('AZ') },
	{ code: 'TM', name: 'Turkmenistan', dialCode: '+993', flagUrl: getFlagUrl('TM') },
	{ code: 'TJ', name: 'Tajikistan', dialCode: '+992', flagUrl: getFlagUrl('TJ') },
	{ code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flagUrl: getFlagUrl('KG') },
	{ code: 'KP', name: 'North Korea', dialCode: '+850', flagUrl: getFlagUrl('KP') },
	{ code: 'TL', name: 'East Timor', dialCode: '+670', flagUrl: getFlagUrl('TL') },
	{ code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flagUrl: getFlagUrl('PG') },
	{ code: 'FJ', name: 'Fiji', dialCode: '+679', flagUrl: getFlagUrl('FJ') },
	{ code: 'NC', name: 'New Caledonia', dialCode: '+687', flagUrl: getFlagUrl('NC') },
	{ code: 'PF', name: 'French Polynesia', dialCode: '+689', flagUrl: getFlagUrl('PF') },
	{ code: 'WS', name: 'Samoa', dialCode: '+685', flagUrl: getFlagUrl('WS') },
	{ code: 'TO', name: 'Tonga', dialCode: '+676', flagUrl: getFlagUrl('TO') },
	{ code: 'VU', name: 'Vanuatu', dialCode: '+678', flagUrl: getFlagUrl('VU') },
	{ code: 'SB', name: 'Solomon Islands', dialCode: '+677', flagUrl: getFlagUrl('SB') },
	{ code: 'KI', name: 'Kiribati', dialCode: '+686', flagUrl: getFlagUrl('KI') },
	{ code: 'TV', name: 'Tuvalu', dialCode: '+688', flagUrl: getFlagUrl('TV') },
	{ code: 'NR', name: 'Nauru', dialCode: '+674', flagUrl: getFlagUrl('NR') },
	{ code: 'PW', name: 'Palau', dialCode: '+680', flagUrl: getFlagUrl('PW') },
	{ code: 'FM', name: 'Micronesia', dialCode: '+691', flagUrl: getFlagUrl('FM') },
	{ code: 'MH', name: 'Marshall Islands', dialCode: '+692', flagUrl: getFlagUrl('MH') },
	{ code: 'GT', name: 'Guatemala', dialCode: '+502', flagUrl: getFlagUrl('GT') },
	{ code: 'BZ', name: 'Belize', dialCode: '+501', flagUrl: getFlagUrl('BZ') },
	{ code: 'SV', name: 'El Salvador', dialCode: '+503', flagUrl: getFlagUrl('SV') },
	{ code: 'HN', name: 'Honduras', dialCode: '+504', flagUrl: getFlagUrl('HN') },
	{ code: 'NI', name: 'Nicaragua', dialCode: '+505', flagUrl: getFlagUrl('NI') },
	{ code: 'CR', name: 'Costa Rica', dialCode: '+506', flagUrl: getFlagUrl('CR') },
	{ code: 'PA', name: 'Panama', dialCode: '+507', flagUrl: getFlagUrl('PA') },
	{ code: 'CU', name: 'Cuba', dialCode: '+53', flagUrl: getFlagUrl('CU') },
	{ code: 'JM', name: 'Jamaica', dialCode: '+1', flagUrl: getFlagUrl('JM') },
	{ code: 'HT', name: 'Haiti', dialCode: '+509', flagUrl: getFlagUrl('HT') },
	{ code: 'DO', name: 'Dominican Republic', dialCode: '+1', flagUrl: getFlagUrl('DO') },
	{ code: 'PR', name: 'Puerto Rico', dialCode: '+1', flagUrl: getFlagUrl('PR') },
	{ code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1', flagUrl: getFlagUrl('TT') },
	{ code: 'BB', name: 'Barbados', dialCode: '+1', flagUrl: getFlagUrl('BB') },
	{ code: 'BS', name: 'Bahamas', dialCode: '+1', flagUrl: getFlagUrl('BS') },
	{ code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1', flagUrl: getFlagUrl('AG') },
	{ code: 'DM', name: 'Dominica', dialCode: '+1', flagUrl: getFlagUrl('DM') },
	{ code: 'GD', name: 'Grenada', dialCode: '+1', flagUrl: getFlagUrl('GD') },
	{ code: 'LC', name: 'Saint Lucia', dialCode: '+1', flagUrl: getFlagUrl('LC') },
	{ code: 'VC', name: 'Saint Vincent', dialCode: '+1', flagUrl: getFlagUrl('VC') },
	{ code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1', flagUrl: getFlagUrl('KN') },
	{ code: 'UY', name: 'Uruguay', dialCode: '+598', flagUrl: getFlagUrl('UY') },
	{ code: 'PY', name: 'Paraguay', dialCode: '+595', flagUrl: getFlagUrl('PY') },
	{ code: 'BO', name: 'Bolivia', dialCode: '+591', flagUrl: getFlagUrl('BO') },
	{ code: 'EC', name: 'Ecuador', dialCode: '+593', flagUrl: getFlagUrl('EC') },
	{ code: 'GY', name: 'Guyana', dialCode: '+592', flagUrl: getFlagUrl('GY') },
	{ code: 'SR', name: 'Suriname', dialCode: '+597', flagUrl: getFlagUrl('SR') },
	{ code: 'GF', name: 'French Guiana', dialCode: '+594', flagUrl: getFlagUrl('GF') },
	{ code: 'FK', name: 'Falkland Islands', dialCode: '+500', flagUrl: getFlagUrl('FK') },
];
